"""
HomGar API - Backward Compatibility Layer.

This module provides backward compatibility for existing imports.
All functionality has been moved to the api/ subpackage.

For new code, please import directly from the api subpackage:
    from .api import HomGarClient
    from .api.decoders import decode_htv213frf_valve
"""

# Import everything from the new api package for backward compatibility
from .api import (
    HomGarClient,
    decode_htv213frf_valve,
    decode_moisture_full,
    decode_moisture_simple,
    decode_hws019wrf_v2,
    decode_valve_hub,
    decode_rain,
    decode_flow_meter,
    decode_flowmeter,  # Alias for backward compatibility
    decode_pool_plus,
    decode_soil,
    decode_temp_hum,
    decode_temp_hum_full,
    decode_co2,
    decode_display,
    decode_unknown,
    decode_temphum,
    decode_pool,
    decode_hcs005frf,
    decode_hcs003frf,
    decode_hcs024frf_v1,
    decode_hcs014arf,
    decode_hcs015arf,
    decode_hcs0528arf,
    decode_hcs027arf,
    decode_hcs016arf,
    decode_hcs044frf,
    decode_hcs666frf,
    decode_hcs666rfr_p,
    decode_hcs999frf,
    decode_hcs999frf_p,
    decode_hcs666frf_x,
    decode_hcs701b,
    decode_hcs596wb,
    decode_hcs596wb_v4,
    decode_hcs706arf,
    decode_hcs802arf,
    decode_hcs048b,
    decode_hcs888arf_v1,
    decode_hcs0600arf,
    _validate_payload,
    _validate_tag,
    _extract_rssi,
    _extract_status_code,
    _battery_status_to_percent,
    _parse_homgar_payload,
    _parse_tlv_payload,
    _le16,
    _f10_to_c,
    _base_decoder_dict,
)

# Import HomGarApiError from client module
from .api.client import HomGarApiError

# Re-export for backward compatibility
__all__ = [
    'HomGarClient',
    'HomGarApiError',
    'decode_htv213frf_valve',
    'decode_moisture_full',
    'decode_moisture_simple',
    'decode_hws019wrf_v2',
    'decode_valve_hub',
    'decode_rain',
    'decode_flow_meter',
    'decode_flowmeter',  # Alias for backward compatibility
    'decode_pool_plus',
    'decode_soil',
    'decode_temp_hum',
    'decode_temp_hum_full',
    'decode_co2',
    'decode_display',
    'decode_unknown',
    'decode_temphum',
    'decode_pool',
    'decode_hcs005frf',
    'decode_hcs003frf',
    'decode_hcs024frf_v1',
    'decode_hcs014arf',
    'decode_hcs015arf',
    'decode_hcs0528arf',
    'decode_hcs027arf',
    'decode_hcs016arf',
    'decode_hcs044frf',
    'decode_hcs666frf',
    'decode_hcs666rfr_p',
    'decode_hcs999frf',
    'decode_hcs999frf_p',
    'decode_hcs666frf_x',
    'decode_hcs701b',
    'decode_hcs596wb',
    'decode_hcs596wb_v4',
    'decode_hcs706arf',
    'decode_hcs802arf',
    'decode_hcs048b',
    'decode_hcs888arf_v1',
    'decode_hcs0600arf',
    '_validate_payload',
    '_validate_tag',
    '_extract_rssi',
    '_extract_status_code',
    '_battery_status_to_percent',
    '_parse_homgar_payload',
    '_parse_tlv_payload',
    '_le16',
    '_f10_to_c',
    '_base_decoder_dict',
]
