"""Device representation for RainPoint hubs and sub-devices."""

from __future__ import annotations

from homeassistant.helpers.device_registry import CONNECTION_NETWORK_MAC, DeviceInfo, format_mac
from homeassistant.helpers.entity import Entity

from .const import DOMAIN, HUB_IDENTIFIER_PREFIX, HUB_UNIQUE_ID_PREFIX


def build_sub_device_info(sensor_info: dict) -> DeviceInfo:
    """Return the device registry entry for one sub-device.

    Every module that owns sub-device entities routes through here, so the
    device page carries the same identity, firmware and hub link no matter
    which platform registered the device first. Five modules used to build
    this dict inline and had drifted: none carried the firmware the
    coordinator already had, and only the sensor platform linked the device to
    its hub. There are four direct call sites today (entity.py, valve.py,
    number.py, generic_control.py); sensor.py and diagnostic_sensors.py were
    later collapsed onto entity.py's shared RainPointSubDeviceEntity base.

    serial_number is the mid/addr pair rather than a manufacturer serial, which the
    status payloads do not carry. It is the same identity the entity unique IDs
    are built from, so it is stable across restarts and re-pairings that keep
    the device in place.

    A cloud-unnamed sub-device's fallback name is computed here, once, as
    "{model} {addr}", falling back further to "Device {addr}" when the record
    carries no model either. It used to be a caller-supplied literal, and the
    four callers had drifted to four different spellings ("Sensor {addr}",
    "Valve Hub {addr}", "Device {addr}" twice with different call sites), so a
    single cloud-unnamed device could register under a different device-page
    name depending on which platform happened to reach the device registry
    first. That race was invisible while every entity's own display name
    still carried the device-name prefix inline, because the mismatch never
    reached the screen. Once display names compose through Home Assistant's
    own device-name prefix instead, the race would have become the visible
    prefix on every one of that device's entity rows, so unifying it here
    closes it rather than deferring it.

    Two consequences follow, both display-only. Upgrading an install that
    already has a cloud-unnamed sub-device renames that device's page in
    place to the unified spelling; a device the user has since renamed
    carries its own override and is untouched, since only the integration's
    own supplied name changes. And a fresh install of a cloud-unnamed
    sub-device now generates a different entity id than it used to, because
    the id's device-name segment is now sourced from this fallback instead of
    from a value inlined into the entity's own name; an existing install's
    entity ids are never regenerated by a device rename, so this affects only
    a device paired for the first time after this change ships.

    A function rather than a base class: the platform entities all descend
    from CoordinatorEntity with their own __init__ chains. A sub-device base
    class shipped alongside RainPointHubDevice originally and no platform ever
    inherited from it, which is how the inline copies drifted in the first
    place.

    The hub link is conditional. via_device is included only when
    sensor_info's stamped "hub_paired" field is truthy: the link is to the
    top-level record that actually carries this sub-device, and a record that
    is not a real hub yields a parentless top-level device, because the
    Bluetooth wrapper record carries no identity fields to build a device page
    from. The verdict is read off the sensor entry rather than re-derived
    here, so there is one predicate for the question rather than a third
    spelling of it. A sensor_info with no "hub_paired" key defaults to
    hub-linked, so a caller that omits the key gets today's behaviour rather
    than a silently orphaned device.

    via_device is omitted rather than passed as None. Both spellings resolve
    identically inside Home Assistant's device registry, so this is not a
    correctness distinction; the reason to prefer omission is readability at
    the call site, a key that is never constructed states "this device has no
    parent" more plainly than a key carrying None, and it is what lets a test
    assert by key membership rather than by equality against None, which would
    pass for either construction. via_device is the first and only
    conditionally-constructed key in this function; every other key is always
    present.
    """
    hid = sensor_info["hid"]
    mid = sensor_info["mid"]
    addr = sensor_info["addr"]
    model = sensor_info.get("model")
    optional: dict = {}
    if sensor_info.get("hub_paired", True):
        # The mid here is the carrying top-level record's, which is exactly the
        # hub's, because the sensor key is {hid}_{mid}_{addr}. Both sides of
        # this link read mid through a direct index, so neither can degrade to
        # a spelling the other does not produce.
        optional["via_device"] = (DOMAIN, f"{HUB_IDENTIFIER_PREFIX}{hid}_{mid}")
    return DeviceInfo(
        identifiers={(DOMAIN, f"{hid}_{mid}_{addr}")},
        name=sensor_info.get("sub_name") or (f"{model} {addr}" if model else f"Device {addr}"),
        manufacturer="RainPoint",  # RainPoint is the actual device manufacturer
        model=model or "Unknown",
        sw_version=sensor_info.get("firmware_version"),
        serial_number=f"{mid}_{addr}",
        **optional,
    )


class RainPointHubDevice(Entity):
    """Base class for RainPoint hub devices."""

    _attr_has_entity_name = True

    def __init__(
        self,
        hub_info: dict,
    ) -> None:
        """Bind this entity to one hub record.

        hub_info is the raw top-level device record the coordinator collected,
        with hid and brand injected. This is a snapshot taken at construction
        time, not a live view: `_collect_hubs` allocates a fresh dict for the
        hub every poll, and no class in this package reassigns this stored
        reference afterward, so the attribute stays frozen at whatever it read
        on the entity's first build for its entire lifetime. An entity needing
        a value that changes after setup must read `self.coordinator.data` in
        its own property instead of this attribute -- the hub broadcast
        switch's `is_on` is the example that does so.

        Hub identity is the pair of the home id and the carrying record's mid,
        not the home id alone: a home can hold more than one hub, and every
        hub-level entity in a home would otherwise contend for one id, which
        Home Assistant resolves by dropping the loser's entities silently.

        mid is direct-indexed rather than defaulted, and that is deliberate.
        The sub-device via_device tuple direct-indexes the same value, so a
        placeholder on this side alone would emit a parent identifier no device
        row carries and orphan every sub-device. A hub record with no mid
        raises here instead, which no live poll can reach: the coordinator
        direct-indexes the same field twice while shaping its data.
        """
        self._hub_info = hub_info
        self._attr_unique_id = f"{HUB_UNIQUE_ID_PREFIX}{hub_info['hid']}_{hub_info['mid']}"
        self._attr_should_poll = False

    @property
    def device_info(self) -> DeviceInfo:
        """Return device registry information for this hub.

        The hub's MAC is reported through connections rather than as a
        serial_number. It used to fill serial_number, which put a MAC address
        behind a "Serial number:" label on the device page while the MAC
        diagnostic sensor displayed the identical value one card away. The
        cloud carries no manufacturer serial for a hub, so no value replaces
        it and the field is simply absent.

        Only identifiers keys the device registry entry here, and it is
        unchanged, so an install upgrading into this keeps its device row,
        its entities and their history. connections is an additional matching
        key rather than a replacement one: Home Assistant merges a device that
        another integration registers under the same MAC into this row, which
        is what the field is for.

        connections is omitted rather than passed empty when the record has no
        usable mac, following via_device in build_sub_device_info. format_mac
        normalises to the lowercase colon-separated spelling the registry
        compares on, so a cloud record's uppercase mac still matches another
        integration's lowercase one. It returns its input unchanged when that
        input is not MAC-shaped, so the truthiness check is on the formatted
        value: an empty or whitespace mac yields no connection at all rather
        than a connection to the empty string, which would match every other
        hub in the same state and merge them into one device row.
        """
        optional: dict = {}
        mac = format_mac(self._hub_info.get("mac") or "").strip()
        if mac:
            optional["connections"] = {(CONNECTION_NETWORK_MAC, mac)}
        return DeviceInfo(
            identifiers={(DOMAIN, f"{HUB_IDENTIFIER_PREFIX}{self._hub_info['hid']}_{self._hub_info['mid']}")},
            name=self._hub_info.get("name") or "RainPoint Hub",
            manufacturer="RainPoint",  # RainPoint is the actual device manufacturer
            model=self._hub_info.get("model") or "Unknown",
            sw_version=self._hub_info.get("softVer"),
            hw_version=self._hub_info.get("hardwareVersion"),
            **optional,
        )

    @property
    def available(self) -> bool:
        return True  # Hub is always available if config exists
